[build]
  publish = "/"
  command = "# no build command needed for static site"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.11.1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https://generativelanguage.googleapis.com;
      style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      connect-src 'self' https://generativelanguage.googleapis.com;
      img-src 'self' data: https:;
      font-src 'self' data: https:;
    """
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, content-type, Authorization"

# Specific headers for JavaScript modules
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[dev]
  framework = "#static"
  targetPort = 8080